version: '3.8'

services:
  CryptoChartPrice:
    image: node:20
    container_name: CryptoChartPrice
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["sh", "-c", "npm install && npm run start"]
